// ASPECT-RANGE PROBE — at what plot aspect does each of these types still READ?
//
// `skills/chart-beat/scripts/type-at-size.mjs` refuses every tall frame for a type it has no
// MEASURED_ASPECT row for, and names the missing measurement as the reason. That refusal is honest
// and it is the wrong answer for five types this corpus already draws: `waterfall`, `slope`,
// `small-multiples`, `bump` and `population-pyramid`. This probe is the measurement it asks for.
// It also RE-measures `line`, whose recorded 0.8–1.8 was taken at 900x560 and at the earlier
// probe's frames, never at 16:9, while this corpus's own accepted landscape line measures 1.94:1.
//
// ── HOW THIS DIFFERS FROM `portrait-aspect-probe/portrait-probe.mjs` ──────────────────────────
//
// That probe derived a range from THREE points: it rendered the type's stretch arm at 900x560,
// 1920x1080 and 1080x1080 and took the extremes. Two things are wrong with three points as a
// method, and the file itself records the first: the 1080x1080 render "was itself already
// stretched", so the line's floor of 0.8 is the aspect of a picture nobody would publish, written
// down as if it were a bound. The second is that three accepted frames cannot bracket a bound they
// never straddle — the same file's 1.8 ceiling for a line is below this corpus's own accepted
// landscape line at 1.94:1.
//
// So this probe SWEEPS. For each type it holds the plot's WIDTH and the type size constant and
// varies the plot's HEIGHT, so aspect is the only thing that changes between two arms of the same
// type; every arm is written out as a PNG and a person opens it. The range recorded is where the
// geometry still reads, and `ASPECT-VERDICT.md` beside this file says what was seen at each arm.
// `ASPECT-MEASUREMENTS.md` is generated by this script and holds only what the instrument measured.
//
// ── WHAT IT DRAWS, AND WHAT IT DELIBERATELY DOES NOT ─────────────────────────────────────────
//
// The PLOT and the labels that live in it or against it — marks, gridlines, tick labels, category
// and series names, value labels. No title, no standfirst, no credit. That is not a shortcut: a
// `MEASURED_ASPECT` row is consumed by `assertPlotAspect`, which is handed the PLOT rectangle, and
// what the furniture above the plot costs is the removal ladder's question, not this one. Two
// separate measurements is exactly why the ladder exists as its own list.
//
// The GEOMETRY IS THE BEAT'S OWN. Every `*Geometry` function below is imported from the beat that
// ships that type, not re-derived here — a probe that re-implemented the scales would measure its
// own arithmetic. The DRAWING is this file's, because a beat's component is one block of frame,
// header, plot and credit, and only the plot is under test.
//
// Usage, from the repository root:  bun proof/aspect-range-probe/render.mjs
//                                   bun proof/aspect-range-probe/render.mjs --only line
//                                   bun proof/aspect-range-probe/render.mjs --aspects 1.9,2.1

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import { scaleLinear } from "d3-scale";
import {
  readPalette,
  deriveFurniture,
  measureText,
  seriesInks,
  FONT_FAMILY,
} from "#shared/chart-beat/render-still.mjs";
import { waterfallGeometry } from "../static-germany-electricity-bridge/ElectricityBridgeWaterfall.tsx";
import { slopeGeometry } from "../static-renewables-shift/RenewablesShiftSlope.tsx";
import { gridGeometry } from "../static-small-multiples-solar-eu-six/SolarSmallMultiples.tsx";
import { bumpGeometry } from "../static-bump-emitter-rank/EmitterRankBump.tsx";
import { pyramidGeometry } from "../static-swiss-age-pyramid/SwissAgePyramid.tsx";
import { lineGeometry } from "../more-line-swiss-life-expectancy/LifeExpectancyLine.tsx";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = HERE;

// ─────────────────────────────────────────────────────────────────────────────────────────────
// THE ONE THING HELD CONSTANT ACROSS EVERY ARM
//
// Plot WIDTH, and the type size. A landscape static's plot is ~1500px wide inside a 1920 frame and
// its floor is 26px (`sizes.mjs`, the article reference); 900px of plot at 26px type is the same
// ratio of type to plot and keeps a 0.5:1 arm's frame under 2,000px tall, which is a picture a
// person can actually open. What matters is that it does not vary: if the type or the width moved
// between arms, a difference the eye reported could not be attributed to the aspect.
//
// BOTH ARE KNOBS, and the second regime is not decoration. A range measured at one ratio of type to
// plot is only transferable if that ratio is the one the frame really gives: a square 1080 frame
// draws at a 36px floor (`sizes.mjs`, the phone's reading distance) into a plot roughly 700px wide,
// which is 1.8x this default's type-to-plot ratio. `--plot-width 700 --type-px 36` reproduces that
// regime, and it is what settles whether a bound learned at the article's regime holds at the
// phone's. Anything printed by this script names the regime it was measured in.
let PLOT_W = 900;
let TYPE = { TICK: 26, LABEL: 28, NAME: 28 };
const AIR = 14;

/**
 * THE ARMS THAT WERE ACTUALLY RENDERED AND OPENED, as data, so `bun render.mjs` with no argument
 * reproduces exactly the set committed beside this file and `ASPECT-VERDICT.md` can name each one.
 *
 * Each type gets a coarse sweep first and then refinement arms either side of wherever the coarse
 * sweep put the break — which is why the lists are not the same length. A range whose bound was
 * never bracketed by two arms, one that reads and one that does not, is a guess with a decimal
 * point on it.
 */
const PLAN = [
  { type: "waterfall", aspects: [0.35, 0.5, 0.9, 1.5, 2.4, 3.6, 4.6, 6.0] },
  { type: "slope", aspects: [0.35, 0.5, 0.9, 1.5, 1.8, 2.0, 2.2, 2.4, 3.6] },
  { type: "small-multiples", aspects: [0.5, 0.9, 1.1, 1.2, 1.3, 1.5, 2.4, 3.6] },
  { type: "bump", aspects: [0.5, 0.9, 1.5, 2.4, 2.9, 3.2, 3.6] },
  { type: "population-pyramid", aspects: [0.5, 0.9, 1.2, 1.5, 1.8, 2.4, 3.6] },
  { type: "line", aspects: [0.5, 0.7, 0.83, 0.9, 1.5, 1.9, 2.4, 2.9, 3.6, 4.5] },
  // The line again at the phone's own regime, because a bound learned at one ratio of type to plot
  // is worth nothing until it has been checked at the other one this toolchain actually exports.
  { type: "line", aspects: [0.7, 0.83, 1.0, 1.3, 1.8, 2.6], plotWidth: 700, typePx: 36 },
  // And the configuration that really broke: two series and a reference level, at the plot width a
  // 1080 square frame gives them (700px) and at the width `vidx-line-life-expectancy` actually got
  // once its own end-label gutter had been paid for (370px). Same aspect, two different pictures.
  { type: "line-two-series", aspects: [0.83, 1.2, 1.6, 2.0], plotWidth: 700, typePx: 36 },
  { type: "line-two-series", aspects: [0.83, 1.5], plotWidth: 370, typePx: 36 },
];

const bold = (fontSize) => ({ fontSize, fontWeight: 700 });
const plain = (fontSize) => ({ fontSize, fontWeight: 400 });

function parseCsv(text) {
  const [header, ...rows] = text.trim().split(/\r?\n/);
  const cols = header.split(",");
  return rows
    .filter((r) => r.length > 0)
    .map((row) => {
      const cells = row.split(",");
      const rec = {};
      cols.forEach((c, i) => (rec[c] = cells[i]));
      return rec;
    });
}

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function text(content, x, y, { fontSize, fontWeight = 400, fill, anchor = "start" }) {
  return (
    `<text x="${round(x)}" y="${round(y)}" font-family="${FONT_FAMILY}" font-size="${fontSize}" ` +
    `font-weight="${fontWeight}" fill="${fill}"` +
    (anchor === "start" ? "" : ` text-anchor="${anchor}"`) +
    `>${esc(content)}</text>`
  );
}

const round = (v) => Math.round(v * 10) / 10;

/** Words to lines, at a measured width — the same shape every beat here carries. */
function wrap(string, maxWidth, font) {
  const lines = [];
  let current = "";
  for (const word of String(string).split(/\s+/)) {
    const trial = current ? `${current} ${word}` : word;
    if (current && measureText(trial, font) > maxWidth) {
      lines.push(current);
      current = word;
    } else current = trial;
  }
  return current ? [...lines, current] : lines;
}

function page(body, width, height, ground) {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" ` +
    `viewBox="0 0 ${width} ${height}">` +
    `<rect x="0" y="0" width="${width}" height="${height}" fill="${ground}"/>` +
    body.join("") +
    `</svg>`
  );
}

/** The frame a plot of `PLOT_W x (PLOT_W / aspect)` needs, given its own gutters. */
function frameFor(aspect, padding) {
  const plotH = PLOT_W / aspect;
  return {
    width: Math.round(PLOT_W + padding.left + padding.right),
    height: Math.round(plotH + padding.top + padding.bottom),
    plotW: PLOT_W,
    plotH,
  };
}

// ─────────────────────────────────────────────────────────────────────────────────────── beats

async function waterfallBeat() {
  const RENEWABLES = ["Other renewables", "Bioenergy", "Solar", "Wind", "Hydropower"];
  const FOSSIL = ["Gas", "Oil", "Coal"];
  const rows = parseCsv(await readFile(join(HERE, "waterfall-generation.csv"), "utf8"));
  const sum = (row, cols) => cols.reduce((s, c) => s + Number(row[c]), 0);
  const at = (year) => {
    const row = rows.find((r) => r.Year === year);
    const renewables = sum(row, RENEWABLES);
    const fossil = sum(row, FOSSIL);
    const nuclear = Number(row.Nuclear);
    return { renewables, nuclear, fossil, total: renewables + nuclear + fossil };
  };
  const years = [...new Set(rows.map((r) => r.Year))].sort();
  const first = at(years[0]);
  const last = at(years[1]);
  const one = (v) => Math.round(v * 10) / 10;
  return [
    { label: `${years[0]} total`, value: one(first.total), kind: "total" },
    { label: "Renewables", value: one(last.renewables - first.renewables), kind: "increase" },
    { label: "Nuclear", value: one(last.nuclear - first.nuclear), kind: "decrease" },
    { label: "Fossil fuel", value: one(last.fossil - first.fossil), kind: "decrease" },
    { label: `${years[1]} total`, value: one(last.total), kind: "total" },
  ];
}

async function slopeBeat() {
  const RENEWABLES = ["Other renewables", "Bioenergy", "Solar", "Wind", "Hydropower"];
  const ALL = [...RENEWABLES, "Nuclear", "Gas", "Oil", "Coal"];
  const rows = parseCsv(await readFile(join(HERE, "slope-generation.csv"), "utf8"));
  const share = (row) => {
    const total = ALL.reduce((s, c) => s + Number(row[c]), 0);
    return (RENEWABLES.reduce((s, c) => s + Number(row[c]), 0) / total) * 100;
  };
  const byCountry = new Map();
  for (const r of rows) {
    if (!byCountry.has(r.Entity)) byCountry.set(r.Entity, {});
    byCountry.get(r.Entity)[r.Year] = share(r);
  }
  const years = [...new Set(rows.map((r) => r.Year))].sort();
  return {
    years,
    series: [...byCountry.entries()]
      .map(([name, y]) => ({ name, start: y[years[0]], end: y[years[1]] }))
      .sort((a, b) => b.end - a.end),
  };
}

async function smallMultiplesBeat() {
  const rows = parseCsv(await readFile(join(HERE, "small-multiples-solar.csv"), "utf8"));
  const countries = [...new Set(rows.map((r) => r.Entity))];
  const panels = countries.map((country) => ({
    country,
    readings: rows
      .filter((r) => r.Entity === country)
      .map((r) => ({ year: Number(r.Year), value: Number(r.Solar) }))
      .sort((a, b) => a.year - b.year),
  }));
  return panels.sort((a, b) => b.readings.at(-1).value - a.readings.at(-1).value);
}

async function bumpBeat() {
  const rows = parseCsv(await readFile(join(HERE, "bump-ranks.csv"), "utf8"));
  const years = [...new Set(rows.map((r) => Number(r.year)))].sort((a, b) => a - b);
  const byCountry = new Map();
  for (const r of rows) {
    if (!byCountry.has(r.country)) byCountry.set(r.country, new Map());
    byCountry.get(r.country).set(Number(r.year), Number(r.rank));
  }
  const tracks = [...byCountry.entries()]
    .map(([country, ranks]) => ({ country, ranks: years.map((y) => ranks.get(y)) }))
    .sort((a, b) => a.ranks.at(-1) - b.ranks.at(-1));
  return { years, tracks, rankRows: Math.max(...tracks.flatMap((t) => t.ranks)) };
}

async function pyramidBeat() {
  const rows = parseCsv(await readFile(join(HERE, "pyramid-bands.csv"), "utf8"));
  return rows.map((r) => ({
    ageBand: r.age_band,
    male: Number(r.male),
    female: Number(r.female),
  }));
}

async function lineBeat() {
  const rows = parseCsv(await readFile(join(HERE, "line-life-expectancy.csv"), "utf8"));
  return rows
    .map((r) => ({ year: Number(r.Year), value: Number(r["Life expectancy"]) }))
    .filter((r) => r.year >= 1950)
    .sort((a, b) => a.year - b.year);
}

/**
 * THE CONFIGURATION THAT ACTUALLY BROKE. `proof/vidx-line-life-expectancy` at square passes both
 * guards at 0.83:1 and is a chart nobody should publish, and its BRIEF names the two reasons: the
 * "80 years" reference label lies across both lines, and the two end labels overflow the plot. A
 * single-series arm cannot reproduce either — one end label has nothing to collide with and a
 * reference rule drawn under one line crosses one line. So the line is measured TWICE: once as one
 * series, and once as the two series and the reference level this corpus really draws.
 *
 * Its own frozen copy of that beat's OWID export, and its own year window and reference level read
 * out of the beat's `BRIEF.md` figures rather than retyped as a guess.
 */
async function lineTwoSeriesBeat() {
  const rows = parseCsv(await readFile(join(HERE, "line-two-series.csv"), "utf8"));
  const FIRST_YEAR = 1990;
  const series = [...new Set(rows.map((r) => r.Entity))].map((name) => ({
    name,
    readings: rows
      .filter((r) => r.Entity === name && Number(r.Year) >= FIRST_YEAR)
      .map((r) => ({ year: Number(r.Year), value: Number(r["Life expectancy"]) }))
      .sort((a, b) => a.year - b.year),
  }));
  const last = Math.min(...series.map((s) => s.readings.at(-1).year));
  return {
    series: series.map((s) => ({ ...s, readings: s.readings.filter((r) => r.year <= last) })),
    reference: 80,
    referenceLabel: "80 years",
  };
}

// ────────────────────────────────────────────────────────────────────────────────────── drawing
//
// One `draw(aspect)` per type. Each returns `{ svg, width, height, plot, facts }` — `facts` being
// the geometry quantity that carries THAT type's argument, which is the whole reason the earlier
// probe reported "tallest mark h:w" for a histogram and slope in degrees for a line. A number that
// says 1080x1920 proves the frame, not the reading.

function drawWaterfall(steps, palette, aspect) {
  const { ink, muted, grid } = deriveFurniture(palette.ground);
  const [increaseFill, decreaseFill] = seriesInks(palette, 2);
  const tickHint = 5;
  // The gutters are MEASURED off the labels that go in them, so nothing in the plot is squeezed by
  // a reserve chosen for a different frame.
  const provisional = scaleLinear().domain([0, 700]).nice().ticks(tickHint);
  const left = Math.max(...provisional.map((t) => measureText(String(t), plain(TYPE.TICK)))) + AIR;
  const labelBand = TYPE.LABEL * 2 + AIR * 2;
  const padding = { top: TYPE.LABEL + AIR * 2, right: AIR * 3, bottom: labelBand, left: left + AIR };
  const frame = frameFor(aspect, padding);
  const geo = waterfallGeometry(steps, {
    width: frame.width,
    height: frame.height,
    padding,
    mutedFill: muted,
    increaseFill,
    decreaseFill,
    barGap: 26,
    tickHint,
  });
  const body = [];
  for (const t of geo.ticksY) {
    body.push(
      `<line x1="${geo.plot.left}" x2="${geo.plot.right}" y1="${round(t.y)}" y2="${round(t.y)}" stroke="${grid}" stroke-width="1"/>`,
    );
    body.push(text(t.value, geo.plot.left - AIR, t.y + TYPE.TICK * 0.35, { fontSize: TYPE.TICK, fill: muted, anchor: "end" }));
  }
  let previous = null;
  for (const bar of geo.bars) {
    if (previous)
      body.push(
        `<line x1="${round(previous.x + previous.width)}" x2="${round(bar.x)}" y1="${round(previous.endY)}" y2="${round(previous.endY)}" stroke="${muted}" stroke-width="1.5" stroke-dasharray="4 4"/>`,
      );
    body.push(
      `<rect x="${round(bar.x)}" y="${round(bar.top)}" width="${round(bar.width)}" height="${round(Math.max(bar.bottom - bar.top, 1))}" fill="${bar.fill}"/>`,
    );
    const printed = bar.kind === "total" ? bar.value.toFixed(1) : `${bar.value > 0 ? "+" : "−"}${Math.abs(bar.value).toFixed(1)}`;
    body.push(text(printed, bar.center, bar.top - AIR / 2, { ...bold(TYPE.LABEL), fill: ink, anchor: "middle" }));
    wrap(bar.label, bar.width, plain(TYPE.LABEL)).forEach((line, i) =>
      body.push(text(line, bar.center, geo.plot.bottom + AIR + TYPE.LABEL * (i + 1), { fontSize: TYPE.LABEL, fill: muted, anchor: "middle" })),
    );
    previous = bar;
  }
  const smallest = [...geo.bars].sort((a, b) => (a.bottom - a.top) - (b.bottom - b.top))[0];
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: geo.plot,
    facts: {
      "bar width": round(geo.bars[0].width),
      "shortest step (px)": round(smallest.bottom - smallest.top),
      "shortest step h:w": round((smallest.bottom - smallest.top) / smallest.width),
      "opening bar h:w": round((geo.bars[0].bottom - geo.bars[0].top) / geo.bars[0].width),
    },
  };
}

function drawSlope({ years, series }, palette, aspect) {
  const { ink, muted } = deriveFurniture(palette.ground);
  const label = (s, value) => `${s.name} ${value.toFixed(1)}%`;
  const widest = Math.max(
    ...series.flatMap((s) => [measureText(label(s, s.start), plain(TYPE.NAME)), measureText(label(s, s.end), plain(TYPE.NAME))]),
  );
  const padding = {
    top: TYPE.LABEL + AIR * 2,
    bottom: AIR * 2,
    left: widest + AIR * 2,
    right: widest + AIR * 2,
  };
  const frame = frameFor(aspect, padding);
  const geo = slopeGeometry(series, {
    width: frame.width,
    height: frame.height,
    padding,
    minLabelGap: TYPE.NAME + 4,
  });
  const body = [
    `<line x1="${geo.plot.left}" x2="${geo.plot.left}" y1="${round(geo.plot.top)}" y2="${round(geo.plot.bottom)}" stroke="${muted}" stroke-width="1"/>`,
    `<line x1="${geo.plot.right}" x2="${geo.plot.right}" y1="${round(geo.plot.top)}" y2="${round(geo.plot.bottom)}" stroke="${muted}" stroke-width="1"/>`,
    text(years[0], geo.plot.left, geo.plot.top - AIR, { ...bold(TYPE.LABEL), fill: muted, anchor: "middle" }),
    text(years[1], geo.plot.right, geo.plot.top - AIR, { ...bold(TYPE.LABEL), fill: muted, anchor: "middle" }),
  ];
  let steepest = 0;
  for (const line of geo.lines) {
    const highlighted = line === geo.lines[0];
    const stroke = highlighted ? palette.accent : muted;
    body.push(
      `<line x1="${round(line.start.x)}" y1="${round(line.start.y)}" x2="${round(line.end.x)}" y2="${round(line.end.y)}" stroke="${stroke}" stroke-width="${highlighted ? 4 : 2}"/>`,
    );
    for (const end of [line.start, line.end])
      body.push(`<circle cx="${round(end.x)}" cy="${round(end.y)}" r="5" fill="${stroke}"/>`);
    body.push(
      text(label(line, line.start.value), line.start.x - AIR, line.start.labelY + TYPE.NAME * 0.35, {
        fontSize: TYPE.NAME,
        fontWeight: highlighted ? 700 : 400,
        fill: highlighted ? ink : muted,
        anchor: "end",
      }),
    );
    body.push(
      text(label(line, line.end.value), line.end.x + AIR, line.end.labelY + TYPE.NAME * 0.35, {
        fontSize: TYPE.NAME,
        fontWeight: highlighted ? 700 : 400,
        fill: highlighted ? ink : muted,
      }),
    );
    const deg = (Math.atan2(Math.abs(line.end.y - line.start.y), line.end.x - line.start.x) * 180) / Math.PI;
    steepest = Math.max(steepest, deg);
  }
  // What a slope chart states is which lines cross and how steeply — so the quantity that carries
  // its argument is an ANGLE, exactly as it is for a line (Cleveland's banking, via Heer & Agrawala).
  const gaps = geo.lines
    .map((l) => l.end.labelY)
    .sort((a, b) => a - b)
    .slice(1)
    .map((y, i) => y - geo.lines.map((l) => l.end.labelY).sort((a, b) => a - b)[i]);
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: geo.plot,
    facts: {
      "steepest line (deg)": round(steepest),
      "label rows de-collided at the right end": geo.lines.filter((l) => Math.abs(l.end.labelY - l.end.y) > 0.5).length,
      "tightest label gap (px)": gaps.length ? round(Math.min(...gaps)) : null,
    },
  };
}

/**
 * The beat's own packing rule, copied rather than imported because it is a module-private function
 * in `SolarSmallMultiples.tsx`. Kept identical, and named here so the copy is visible: a wide grid
 * box takes 3 x 2, a tall one 2 x 3, chosen to keep each panel near the 1.6:1 shape this corpus's
 * six panels were drawn and accepted at.
 */
function columnsFor(width, height, panels) {
  const candidates = [1, 2, 3, panels].filter((c, i, all) => c <= panels && all.indexOf(c) === i);
  let best = candidates[0];
  let bestError = Infinity;
  for (const columns of candidates) {
    const rows = Math.ceil(panels / columns);
    const error = Math.abs(Math.log(width / columns / (height / rows) / 1.6));
    if (error < bestError) {
      bestError = error;
      best = columns;
    }
  }
  return best;
}

function drawSmallMultiples(panels, palette, aspect) {
  const { ink, muted, grid } = deriveFurniture(palette.ground);
  const share = (v) => `${v.toFixed(1)}%`;
  const yGutter = 70 + AIR;
  const padding = { top: AIR, right: AIR * 2, bottom: AIR, left: yGutter };
  const frame = frameFor(aspect, padding);
  const columns = columnsFor(PLOT_W, frame.plotH, panels.length);
  const xAxisBand = TYPE.TICK + AIR * 2;
  const geo = gridGeometry(panels, {
    width: frame.width,
    height: frame.height,
    padding,
    columns,
    columnGap: AIR * 3,
    rowGap: AIR * 2,
    panelHeader: TYPE.NAME + AIR,
    xAxisBand,
    endGutter: measureText("00.0%", plain(TYPE.TICK)) + AIR,
  });
  const body = [];
  for (const box of geo.boxes) {
    body.push(
      `<rect x="${round(box.plot.left)}" y="${round(box.plot.top)}" width="${round(box.plot.right - box.plot.left)}" height="${round(Math.max(box.plot.bottom - box.plot.top, 1))}" fill="none" stroke="${grid}" stroke-width="1"/>`,
    );
    body.push(
      `<polyline fill="none" stroke="${palette.accent}" stroke-width="3" points="${box.points.map((p) => `${round(p.cx)},${round(p.cy)}`).join(" ")}"/>`,
    );
    body.push(text(box.panel.country, box.plot.left, box.plot.top - AIR / 2, { ...bold(TYPE.NAME), fill: ink }));
    const end = box.points.at(-1);
    body.push(`<circle cx="${round(end.cx)}" cy="${round(end.cy)}" r="5" fill="${palette.accent}"/>`);
    body.push(text(share(end.value), end.cx + AIR / 2, end.cy + TYPE.TICK * 0.35, { fontSize: TYPE.TICK, fill: ink }));
    if (box.isLeftColumn)
      for (const t of geo.yTicks ?? [])
        body.push(text(share(t), box.plot.left - AIR, box.y(t) + TYPE.TICK * 0.35, { fontSize: TYPE.TICK, fill: muted, anchor: "end" }));
    if (box.isBottomRow)
      for (const year of [box.points[0].year, box.points.at(-1).year])
        body.push(text(year, box.x(year), box.plot.bottom + AIR + TYPE.TICK, { fontSize: TYPE.TICK, fill: muted, anchor: "middle" }));
  }
  const first = geo.boxes[0].plot;
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: {
      left: padding.left,
      top: padding.top,
      right: frame.width - padding.right,
      bottom: frame.height - padding.bottom,
    },
    facts: {
      columns,
      rows: Math.ceil(panels.length / columns),
      "panel box": `${round(first.right - first.left)} x ${round(first.bottom - first.top)}`,
      "panel aspect": round((first.right - first.left) / (first.bottom - first.top)),
    },
  };
}

function drawBump({ years, tracks, rankRows }, palette, aspect) {
  const { ink, muted, grid } = deriveFurniture(palette.ground);
  const widest = Math.max(...tracks.map((t) => measureText(t.country, plain(TYPE.NAME))));
  const padding = {
    top: TYPE.NAME + AIR,
    bottom: TYPE.TICK + AIR * 2,
    left: widest + AIR * 2,
    right: widest + AIR * 2,
  };
  const frame = frameFor(aspect, padding);
  const geo = bumpGeometry(tracks, years, rankRows, {
    width: frame.width,
    height: frame.height,
    padding,
  });
  const body = [];
  for (let rank = 1; rank <= rankRows; rank++)
    body.push(
      `<line x1="${round(geo.plot.left)}" x2="${round(geo.plot.right)}" y1="${round(geo.yOfRank(rank))}" y2="${round(geo.yOfRank(rank))}" stroke="${grid}" stroke-width="1"/>`,
    );
  for (const line of geo.lines) {
    const highlighted = line.country === geo.lines[0].country;
    const stroke = highlighted ? palette.accent : muted;
    body.push(
      `<polyline fill="none" stroke="${stroke}" stroke-width="${highlighted ? 5 : 3}" points="${line.points.map((p) => `${round(p.x)},${round(p.y)}`).join(" ")}"/>`,
    );
    for (const p of line.points)
      body.push(`<circle cx="${round(p.x)}" cy="${round(p.y)}" r="4" fill="${stroke}"/>`);
    body.push(
      text(line.country, geo.plot.left - AIR, line.points[0].y + TYPE.NAME * 0.35, {
        fontSize: TYPE.NAME,
        fontWeight: highlighted ? 700 : 400,
        fill: highlighted ? ink : muted,
        anchor: "end",
      }),
    );
    body.push(
      text(line.country, geo.plot.right + AIR, line.points.at(-1).y + TYPE.NAME * 0.35, {
        fontSize: TYPE.NAME,
        fontWeight: highlighted ? 700 : 400,
        fill: highlighted ? ink : muted,
      }),
    );
  }
  for (const year of [years[0], years[Math.floor(years.length / 2)], years.at(-1)])
    body.push(
      text(year, geo.xOfIndex(years.indexOf(year)), geo.plot.bottom + AIR + TYPE.TICK, {
        fontSize: TYPE.TICK,
        fill: muted,
        anchor: "middle",
      }),
    );
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: geo.plot,
    facts: {
      "rank row pitch (px)": round(geo.rowHeight),
      "year column (px)": round(geo.columnWidth),
      "steepest single-year move (deg)": round(
        Math.max(
          ...geo.lines.flatMap((l) =>
            l.points.slice(1).map((p, i) => (Math.atan2(Math.abs(p.y - l.points[i].y), geo.columnWidth) * 180) / Math.PI),
          ),
        ),
      ),
    },
  };
}

function drawPyramid(bands, palette, aspect) {
  const { ink, muted, grid } = deriveFurniture(palette.ground);
  const bandGutter = Math.max(...bands.map((b) => measureText(b.ageBand, plain(TYPE.TICK)))) + AIR * 2;
  const padding = { top: AIR, right: AIR * 2, bottom: TYPE.TICK + AIR * 2, left: AIR * 2 };
  const frame = frameFor(aspect, padding);
  const geo = pyramidGeometry(bands, {
    width: frame.width,
    height: frame.height,
    padding,
    bandGutter,
  });
  const body = [];
  for (const bar of geo.bars) {
    body.push(
      `<rect x="${round(bar.male_.x)}" y="${round(bar.y)}" width="${round(bar.male_.width)}" height="${round(Math.max(bar.height, 1))}" fill="${palette.accent}"/>`,
    );
    body.push(
      `<rect x="${round(bar.female_.x)}" y="${round(bar.y)}" width="${round(bar.female_.width)}" height="${round(Math.max(bar.height, 1))}" fill="${muted}"/>`,
    );
    body.push(
      text(bar.ageBand, geo.centerX, bar.centerLabelY + TYPE.TICK * 0.35, { fontSize: TYPE.TICK, fill: ink, anchor: "middle" }),
    );
  }
  const thousands = (v) => `${Math.round(v / 1000)}k`;
  for (const t of geo.ticksLeft)
    body.push(text(thousands(t.value), t.x, geo.plot.bottom + AIR + TYPE.TICK, { fontSize: TYPE.TICK, fill: muted, anchor: "middle" }));
  for (const t of geo.ticksRight)
    body.push(text(thousands(t.value), t.x, geo.plot.bottom + AIR + TYPE.TICK, { fontSize: TYPE.TICK, fill: muted, anchor: "middle" }));
  body.push(
    `<line x1="${round(geo.centerX)}" x2="${round(geo.centerX)}" y1="${round(geo.plot.top)}" y2="${round(geo.plot.bottom)}" stroke="${grid}" stroke-width="1"/>`,
  );
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: geo.plot,
    facts: {
      "band pitch (px)": round((geo.plot.bottom - geo.plot.top) / bands.length),
      "bar height (px)": round(geo.bars[0].height),
      "label type (px)": TYPE.TICK,
      "widest bar (px)": round(Math.max(...geo.bars.map((b) => Math.max(b.male_.width, b.female_.width)))),
    },
  };
}

function drawLine(readings, palette, aspect) {
  const { ink, muted, grid } = deriveFurniture(palette.ground);
  const provisional = scaleLinear().domain([readings[0].value, readings.at(-1).value]).nice().ticks(5);
  const left = Math.max(...provisional.map((t) => measureText(String(t), plain(TYPE.TICK)))) + AIR;
  const endLabel = `${readings.at(-1).value.toFixed(1)}`;
  const padding = {
    top: TYPE.LABEL,
    right: measureText(endLabel, bold(TYPE.LABEL)) + AIR * 2,
    bottom: TYPE.TICK + AIR * 2,
    left: left + AIR,
  };
  const frame = frameFor(aspect, padding);
  const geo = lineGeometry(readings, { width: frame.width, height: frame.height, padding });
  const body = [];
  for (const t of geo.ticksY) {
    body.push(
      `<line x1="${round(geo.plot.left)}" x2="${round(geo.plot.right)}" y1="${round(t.y)}" y2="${round(t.y)}" stroke="${grid}" stroke-width="1"/>`,
    );
    body.push(text(t.value, geo.plot.left - AIR, t.y + TYPE.TICK * 0.35, { fontSize: TYPE.TICK, fill: muted, anchor: "end" }));
  }
  for (const t of geo.ticksX)
    body.push(text(t.year, t.x, geo.plot.bottom + AIR + TYPE.TICK, { fontSize: TYPE.TICK, fill: muted, anchor: "middle" }));
  body.push(`<path d="${geo.path}" fill="none" stroke="${palette.accent}" stroke-width="4"/>`);
  body.push(`<circle cx="${round(geo.end.x)}" cy="${round(geo.end.y)}" r="6" fill="${palette.accent}"/>`);
  body.push(text(endLabel, geo.end.x + AIR, geo.end.y + TYPE.LABEL * 0.35, { ...bold(TYPE.LABEL), fill: ink }));
  const deg = (a, b) => (Math.atan2(Math.abs(b.y - a.y), Math.abs(b.x - a.x)) * 180) / Math.PI;
  let steepest = 0;
  for (let i = 1; i < geo.points.length; i++) steepest = Math.max(steepest, deg(geo.points[i - 1], geo.points[i]));
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: geo.plot,
    facts: {
      // Cleveland's banking-to-45deg, as formalised by Heer & Agrawala 2006: the quantity a reader
      // judges a line by is its slope, and slope is exactly what an aspect change destroys.
      "steepest segment (deg)": round(steepest),
      "first to last (deg)": round(deg(geo.points[0], geo.points.at(-1))),
      "gridline pitch (px)": round(Math.abs(geo.ticksY[1].y - geo.ticksY[0].y)),
    },
  };
}

/**
 * The two-series line with its reference level — `vidx-line-life-expectancy`'s own drawing, minus
 * the frame. The plot rectangle and the fitted domain come from `lineGeometry` handed BOTH series
 * plus the reference, exactly as `twoLineGeometry` does it, so the reference always sits inside
 * the frame; the per-series paths are then laid on that one pair of scales.
 *
 * The two things this arm exists to see, and neither is visible on a single series:
 *   - whether the reference label lies across the lines it names;
 *   - whether the two end labels have room to be two labels.
 */
function drawLineTwo({ series, reference, referenceLabel }, palette, aspect) {
  const { ink, muted, grid } = deriveFurniture(palette.ground);
  const [subject, context] = [...series].sort((a, b) => b.readings.at(-1).value - a.readings.at(-1).value);
  const all = series.flatMap((s) => s.readings);
  const withReference = [...all, { year: all[0].year, value: reference }];
  const endLabelOf = (s) => `${s.name} ${s.readings.at(-1).value.toFixed(1)}`;
  const provisional = scaleLinear().domain([Math.min(...all.map((r) => r.value)), Math.max(...all.map((r) => r.value))]).nice().ticks(5);
  const padding = {
    top: TYPE.LABEL,
    right: Math.max(...series.map((s) => measureText(endLabelOf(s), bold(TYPE.LABEL)))) + AIR * 2,
    bottom: TYPE.TICK + AIR * 2,
    left: Math.max(...provisional.map((t) => measureText(String(t), plain(TYPE.TICK)))) + AIR * 2,
  };
  const frame = frameFor(aspect, padding);
  const geo = lineGeometry(withReference, { width: frame.width, height: frame.height, padding });
  const years = all.map((r) => r.year);
  const x = scaleLinear().domain([Math.min(...years), Math.max(...years)]).range([geo.plot.left, geo.plot.right]);
  const y = scaleLinear().domain(geo.domain).range([geo.plot.bottom, geo.plot.top]);
  const body = [];
  for (const t of geo.ticksY) {
    body.push(
      `<line x1="${round(geo.plot.left)}" x2="${round(geo.plot.right)}" y1="${round(y(t.value))}" y2="${round(y(t.value))}" stroke="${grid}" stroke-width="1"/>`,
    );
    body.push(text(t.value, geo.plot.left - AIR, y(t.value) + TYPE.TICK * 0.35, { fontSize: TYPE.TICK, fill: muted, anchor: "end" }));
  }
  for (const t of geo.ticksX)
    body.push(text(t.year, x(t.year), geo.plot.bottom + AIR + TYPE.TICK, { fontSize: TYPE.TICK, fill: muted, anchor: "middle" }));
  const referenceY = y(reference);
  body.push(
    `<line x1="${round(geo.plot.left)}" x2="${round(geo.plot.right)}" y1="${round(referenceY)}" y2="${round(referenceY)}" stroke="${muted}" stroke-width="1.5" stroke-dasharray="6 5"/>`,
  );
  const referenceLabelY = referenceY - AIR / 2;
  body.push(text(referenceLabel, geo.plot.left + AIR, referenceLabelY, { fontSize: TYPE.TICK, fill: muted }));
  const referenceLabelBox = {
    left: geo.plot.left + AIR,
    right: geo.plot.left + AIR + measureText(referenceLabel, plain(TYPE.TICK)),
    top: referenceLabelY - TYPE.TICK * 0.75,
    bottom: referenceLabelY + TYPE.TICK * 0.25,
  };
  let crossings = 0;
  const endLabelYs = [];
  for (const s of [context, subject]) {
    const points = s.readings.map((r) => ({ x: x(r.year), y: y(r.value) }));
    body.push(
      `<polyline fill="none" stroke="${s === subject ? palette.accent : muted}" stroke-width="${s === subject ? 4 : 3}" points="${points.map((p) => `${round(p.x)},${round(p.y)}`).join(" ")}"/>`,
    );
    // Does the reference label's own ink box sit on this line? The count is the finding, measured
    // rather than eyeballed — the eye then confirms it on the arm.
    for (let i = 1; i < points.length; i++) {
      const a = points[i - 1];
      const b = points[i];
      if (Math.max(a.x, b.x) < referenceLabelBox.left || Math.min(a.x, b.x) > referenceLabelBox.right) continue;
      if (Math.min(a.y, b.y) <= referenceLabelBox.bottom && Math.max(a.y, b.y) >= referenceLabelBox.top) {
        crossings += 1;
        break;
      }
    }
    const end = points.at(-1);
    endLabelYs.push(end.y);
    body.push(`<circle cx="${round(end.x)}" cy="${round(end.y)}" r="6" fill="${s === subject ? palette.accent : muted}"/>`);
    body.push(
      text(endLabelOf(s), end.x + AIR, end.y + TYPE.LABEL * 0.35, {
        fontSize: TYPE.LABEL,
        fontWeight: s === subject ? 700 : 400,
        fill: s === subject ? ink : muted,
      }),
    );
  }
  return {
    svg: page(body, frame.width, frame.height, palette.ground),
    frame,
    plot: geo.plot,
    facts: {
      "end-label gutter (px)": round(padding.right),
      "gutter as share of frame": `${Math.round((padding.right / frame.width) * 100)}%`,
      "end labels apart (px)": round(Math.abs(endLabelYs[0] - endLabelYs[1])),
      "lines the reference label lies on": crossings,
    },
  };
}

// ────────────────────────────────────────────────────────────────────────────────────────── run

async function main() {
  const palette = readPalette(HERE, { stopAt: join(HERE, "..") });
  console.log(
    `palette from ${palette.source} — ground ${palette.ground}, accent ${palette.accent}, chosen by ${palette.origin}\n`,
  );

  const onlyAt = process.argv.indexOf("--only");
  const only = onlyAt === -1 ? null : process.argv[onlyAt + 1];
  const aspectsAt = process.argv.indexOf("--aspects");
  const override =
    aspectsAt === -1 ? null : process.argv[aspectsAt + 1].split(",").map(Number);
  const widthAt = process.argv.indexOf("--plot-width");
  const typeAt = process.argv.indexOf("--type-px");

  const drawers = {
    waterfall: { data: await waterfallBeat(), draw: drawWaterfall, from: "static-germany-electricity-bridge" },
    slope: { data: await slopeBeat(), draw: drawSlope, from: "static-renewables-shift" },
    "small-multiples": { data: await smallMultiplesBeat(), draw: drawSmallMultiples, from: "static-small-multiples-solar-eu-six" },
    bump: { data: await bumpBeat(), draw: drawBump, from: "static-bump-emitter-rank" },
    "population-pyramid": { data: await pyramidBeat(), draw: drawPyramid, from: "static-swiss-age-pyramid" },
    line: { data: await lineBeat(), draw: drawLine, from: "more-line-swiss-life-expectancy" },
    "line-two-series": { data: await lineTwoSeriesBeat(), draw: drawLineTwo, from: "vidx-line-life-expectancy" },
  };

  const passes = PLAN.filter((p) => !only || p.type === only).map((p) => ({
    ...p,
    aspects: override ?? p.aspects,
    plotWidth: widthAt === -1 ? (p.plotWidth ?? 900) : Number(process.argv[widthAt + 1]),
    typePx: typeAt === -1 ? (p.typePx ?? 26) : Number(process.argv[typeAt + 1]),
  }));

  await mkdir(join(OUT, "arms"), { recursive: true });
  const rows = [];
  for (const pass of passes) {
    PLOT_W = pass.plotWidth;
    TYPE = { TICK: pass.typePx, LABEL: pass.typePx + 2, NAME: pass.typePx + 2 };
    // A regime is part of an arm's identity, not a footnote: two arms at the same aspect and
    // different regimes are two different pictures and must not overwrite one another.
    const suffix = PLOT_W === 900 && TYPE.TICK === 26 ? "" : `-w${PLOT_W}t${TYPE.TICK}`;
    const { data, draw, from } = drawers[pass.type];
    console.log(`\n${pass.type} — plot width ${PLOT_W}px, type ${TYPE.TICK}/${TYPE.LABEL}px`);
    for (const aspect of pass.aspects) {
      const arm = draw(data, palette, aspect);
      const id = `${pass.type}-${String(aspect).replace(".", "p")}${suffix}`;
      await writeFile(join(OUT, "arms", `${id}.svg`), arm.svg);
      await writeFile(
        join(OUT, "arms", `${id}.png`),
        new Resvg(arm.svg, { font: { loadSystemFonts: true } }).render().asPng(),
      );
      const drawn = (arm.plot.right - arm.plot.left) / (arm.plot.bottom - arm.plot.top);
      rows.push({ type: pass.type, from, regime: `${PLOT_W}px / ${TYPE.TICK}px`, id, arm, drawn });
      console.log(
        `  ${id.padEnd(30)} frame ${String(arm.frame.width).padStart(4)}x${String(arm.frame.height).padStart(4)}  ` +
          `plot ${Math.round(arm.plot.right - arm.plot.left)}x${Math.round(arm.plot.bottom - arm.plot.top)} = ${drawn.toFixed(2)}:1  ` +
          Object.entries(arm.facts).map(([k, v]) => `${k} ${v}`).join(", "),
      );
    }
  }

  const md = [
    "# Aspect-range probe — the measurements, as produced",
    "",
    "Regenerate with `bun proof/aspect-range-probe/render.mjs` from the repository root. Every",
    "number below is written by that script. `ASPECT-VERDICT.md` beside this file is the other half",
    "— what a person saw when the PNGs in `arms/` were opened — and is not generated.",
    "",
    "Within one regime the plot's WIDTH and the type size are held constant, so aspect is the only",
    "quantity that differs between two arms. The `regime` column is `plot width / tick size`: the",
    "default 900/26 is the article's reading distance, and 700/36 and 370/36 are what a 1080-wide",
    "frame really gives a chart at the phone's own 36px floor.",
    "",
    "| type | arm | regime | frame | plot | aspect drawn | what carries the argument |",
    "|---|---|---|---|---|---|---|",
  ];
  for (const r of rows)
    md.push(
      `| ${r.type} | \`arms/${r.id}.png\` | ${r.regime} | ${r.arm.frame.width}x${r.arm.frame.height} | ` +
        `${Math.round(r.arm.plot.right - r.arm.plot.left)}x${Math.round(r.arm.plot.bottom - r.arm.plot.top)} | ` +
        `${r.drawn.toFixed(2)}:1 | ${Object.entries(r.arm.facts).map(([k, v]) => `${k} ${v}`).join("; ")} |`,
    );
  md.push("");
  md.push("## Where each type's geometry comes from");
  md.push("");
  for (const name of [...new Set(rows.map((r) => r.type))])
    md.push(
      `- **${name}** — \`proof/${rows.find((r) => r.type === name).from}/\`, its own \`*Geometry\` ` +
        `export and its own frozen data.`,
    );
  md.push("");
  await writeFile(join(OUT, "ASPECT-MEASUREMENTS.md"), md.join("\n") + "\n");
  console.log(`\nwrote ASPECT-MEASUREMENTS.md and ${rows.length} arms — now open them and look.`);
}

main();
