// twin/scripts/design-base/build-indexes.mjs
//
// THE TWO INDEXES, GENERATED. Never hand-edited, and the guard refuses one without its marker.
//
// The corpus is read twice, on two axes, because the two questions are asked by different people at
// different moments. A journalist's beat has a TYPE and an EXPORT and wants to know what real work
// looks like there; a renderer has a data SHAPE and wants to know which lever applies. One body of
// records, two ways in.
//
// Generated rather than written because the methodology explicitly allows two families to be
// harvested in parallel, and two agents editing one index by hand is a conflict on every run.
//
// Usage:  bun scripts/design-base/build-indexes.mjs

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..");
const BASE = join(ROOT, "docs", "design-base");

export const GENERATED_MARKER =
  "<!-- generated by scripts/design-base/build-indexes.mjs — do not edit -->";

const dirsUnder = (path) =>
  existsSync(path) ? readdirSync(path).filter((n) => statSync(join(path, n)).isDirectory()) : [];
const markdownIn = (path) =>
  existsSync(path) ? readdirSync(path).filter((f) => f.endsWith(".md")) : [];

/** A `- key: value` line out of a record's own front matter. Records are Markdown so a person can
 *  read one without a tool; this is the smallest parse that respects that. */
function field(text, key) {
  return text.match(new RegExp(`^- ${key}:\\s*(.+)$`, "m"))?.[1]?.trim() ?? null;
}

function fields(text, key) {
  return [...text.matchAll(new RegExp(`^- ${key}:\\s*(.+)$`, "gm"))].map((m) => m[1].trim());
}

/** A section's body out of a NOTES.md, so the index can quote the piece's own words. */
function section(text, heading) {
  const at = text.indexOf(heading);
  if (at < 0) return null;
  const rest = text.slice(at + heading.length);
  const end = rest.indexOf("\n## ");
  return (end < 0 ? rest : rest.slice(0, end)).trim().split(/\n\n/)[0]?.replace(/\s+/g, " ").trim() ?? null;
}

function readReferences() {
  const refs = join(BASE, "references");
  const out = [];
  for (const family of dirsUnder(refs))
    for (const id of dirsUnder(join(refs, family))) {
      const dir = join(refs, family, id);
      const measured = JSON.parse(readFileSync(join(dir, "measured.json"), "utf8"));
      const notesPath = join(dir, "NOTES.md");
      const notes = existsSync(notesPath) ? readFileSync(notesPath, "utf8") : "";
      out.push({
        family,
        id,
        url: measured.url,
        archive: measured.archive,
        title: measured.style?.title ?? "",
        shape: measured.pixel?.shape ?? "—",
        ground: measured.pixel?.ground?.hex ?? "—",
        routes: measured.routes,
        what: section(notes, "## What it is"),
        export: field(notes, "export") ?? "—",
        type: field(notes, "type") ?? "—",
      });
    }
  return out.sort((a, b) => a.family.localeCompare(b.family) || a.id.localeCompare(b.id));
}

function readLevers() {
  const out = [];
  for (const kind of ["treatments", "directions"])
    for (const file of markdownIn(join(BASE, kind))) {
      const text = readFileSync(join(BASE, kind, file), "utf8");
      out.push({
        kind: kind.replace(/s$/, ""),
        id: file.replace(/\.md$/, ""),
        name: field(text, "name") ?? "",
        applies: field(text, "applies"),
        evidence: kind === "treatments" ? fields(text, "evidence") : [field(text, "measuredFrom")].filter(Boolean),
      });
    }
  return out.sort((a, b) => a.kind.localeCompare(b.kind) || a.id.localeCompare(b.id));
}

const escape = (s) => String(s ?? "").replace(/\|/g, "\\|");

function byArtifact(references) {
  const rows = references
    .map(
      (r) =>
        `| ${escape(r.family)} | ${escape(r.type)} | ${escape(r.export)} | ${escape(r.archive)} | ${escape(r.shape)} | \`${escape(r.ground)}\` | [${escape(r.id)}](references/${r.family}/${r.id}/NOTES.md) |`,
    )
    .join("\n");
  return `${GENERATED_MARKER}

# Index by artifact

What real work looks like for a given kind of graphic and a given export. The **type** and
**export** columns are each reference's own answer in its \`NOTES.md\`; **shape** is the palette
structure the pixel route measured, in \`100.datavizproject.com\`'s own SHAPE vocabulary where it
applies.

${references.length} reference${references.length === 1 ? "" : "s"}.

| family | type | export | archive | palette shape | ground | reference |
| --- | --- | --- | --- | --- | --- | --- |
${rows || "| — | — | — | — | — | — | *the corpus is empty* |"}
`;
}

function byLever(levers, references) {
  const known = new Map(references.map((r) => [r.id, r]));
  const rows = levers
    .map((l) => {
      const cited = l.evidence
        .map((id) =>
          known.has(id)
            ? `[${escape(id)}](references/${known.get(id).family}/${id}/NOTES.md)`
            : `${escape(id)} *(not in corpus)*`,
        )
        .join("<br>");
      return `| ${escape(l.kind)} | \`${escape(l.id)}\` | ${escape(l.name)} | ${escape(l.applies ?? "—")} | ${cited || "—"} |`;
    })
    .join("\n");
  return `${GENERATED_MARKER}

# Index by lever

What can be lifted, and what backs it. A **treatment** is conditional and plural — several apply to
one beat and an arbiter resolves them. A **direction** is global and exclusive — exactly one governs
a beat.

A treatment is filed only with two independent references; a direction with one, because a direction
is a coherent whole and averaging two would produce neither.

${levers.length} lever${levers.length === 1 ? "" : "s"}.

| kind | id | name | applies when | evidence |
| --- | --- | --- | --- | --- |
${rows || "| — | — | — | — | *nothing filed yet* |"}
`;
}

const references = readReferences();
const levers = readLevers();
await writeFile(join(BASE, "INDEX-BY-ARTIFACT.md"), byArtifact(references));
await writeFile(join(BASE, "INDEX-BY-LEVER.md"), byLever(levers, references));
console.log(
  `indexes rebuilt: ${references.length} reference(s), ${levers.length} lever(s)`,
);
