/**
 * THE FLOOR UNDER THE DESIGN BASE. Collecting is not the deliverable.
 *
 * The branch this work replaces died at 112 harvested thumbnails and four written notes: a corpus
 * that grows by harvesting and never by judgement reaches no pixel and teaches nothing. These are
 * the three floors that make that outcome fail loudly instead of quietly.
 *
 *   1. Every reference carries the five sections a judgement needs — including what was NOT
 *      verified, which is the section a hurried harvest drops first.
 *   2. Every treatment cites two independent references. One use is a publication's habit; two is
 *      a practice. A treatment that cannot find its second reference is not filed, and that is the
 *      guard working rather than an obstacle to route around.
 *   3. Both indexes are generated. Two families harvested in parallel — which the methodology
 *      explicitly allows — would conflict on a hand-edited index.
 */
import { describe, it, expect } from "bun:test";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..", "..", "..");
const BASE = join(ROOT, "docs", "design-base");

const REQUIRED_NOTE_SECTIONS = [
  "## What it is",
  "## What it does with information",
  "## What it does with style",
  "## What is transferable",
  "## What was not verified",
];

const GENERATED_MARKER =
  "<!-- generated by scripts/design-base/build-indexes.mjs — do not edit -->";

function dirsUnder(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path).filter((n) => statSync(join(path, n)).isDirectory());
}

function markdownIn(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path).filter((f) => f.endsWith(".md"));
}

/** The publication behind every reference in the corpus, keyed by id: the host of the url the
 *  record was harvested from, which is the only place independence can honestly be read. */
function publicationById(): Map<string, string> {
  const refs = join(BASE, "references");
  const out = new Map<string, string>();
  for (const family of dirsUnder(refs))
    for (const id of dirsUnder(join(refs, family))) {
      const record = JSON.parse(
        readFileSync(join(refs, family, id, "measured.json"), "utf8"),
      );
      out.set(id, new URL(record.url).hostname.replace(/^www\./, ""));
    }
  return out;
}

describe("the design base", () => {
  it("should give every reference the five sections a judgement needs", () => {
    const refs = join(BASE, "references");
    for (const family of dirsUnder(refs))
      for (const id of dirsUnder(join(refs, family))) {
        const notes = join(refs, family, id, "NOTES.md");
        expect(existsSync(notes), `${family}/${id} has no NOTES.md`).toBe(true);
        const text = readFileSync(notes, "utf8");
        for (const section of REQUIRED_NOTE_SECTIONS)
          expect(text, `${family}/${id} is missing "${section}"`).toContain(
            section,
          );
      }
  });

  it("should say, for every treatment, whether it draws a fact or imports a practice", () => {
    // The two kinds are not a taxonomy for its own sake: they carry different burdens of proof, and
    // a record that does not say which is asking for the wrong one.
    for (const file of markdownIn(join(BASE, "treatments"))) {
      const text = readFileSync(join(BASE, "treatments", file), "utf8");
      const kind = text.match(/^- kind:\s*(\S+)/m)?.[1];
      expect(["derived", "imported"], `${file} declares kind "${kind}"`).toContain(kind);
    }
  });

  it("should require a detect and a rendered proof of every derived treatment", () => {
    // A derived treatment borrows nothing, so no external reference can vouch for it. What stands
    // in its place is that it MUST be measurable on the delivered artifact and MUST have been
    // drawn: "the data already contains it" is not a licence to file an idea.
    for (const file of markdownIn(join(BASE, "treatments"))) {
      const text = readFileSync(join(BASE, "treatments", file), "utf8");
      if (!/^- kind:\s*derived/m.test(text)) continue;
      expect(text, `${file} has no detect`).toMatch(/^- detect:\s*\S/m);
      expect(text, `${file} names no render that proves it`).toMatch(/^- provenBy:\s*\S/m);
    }
  });

  it("should back every IMPORTED treatment with references from at least two distinct publications", () => {
    // TWO RECORDS ARE NOT TWO USES IF THEY CAME FROM THE SAME DESK.
    //
    // A first version of this floor counted distinct reference ids, and the five
    // `100.datavizproject.com` records would have satisfied it on their own — one publication, one
    // house style, one designer, encoding one dataset five ways. That is a habit, which is exactly
    // what the floor exists to exclude. Independence is measured at the PUBLICATION, and the
    // publication is read off each cited record's own url rather than trusted from its id.
    const publications = publicationById();
    for (const file of markdownIn(join(BASE, "treatments"))) {
      const text = readFileSync(join(BASE, "treatments", file), "utf8");
      // A DERIVED treatment draws a fact the beat itself carries — its own geometry, its own
      // declared reference level, its own series. It imports nothing, so there is nothing for a
      // second publication to corroborate. The floor was written against copying a newsroom's
      // habit and mis-applied here refuses honest work: it kept the crossing this beat's own
      // `crossingGeometry` already computes out of the picture for a whole day.
      if (/^- kind:\s*derived/m.test(text)) continue;
      const cited = [
        ...new Set([...text.matchAll(/^- evidence:\s*(\S+)/gm)].map((m) => m[1])),
      ];
      const desks = new Set(cited.map((id) => publications.get(id)).filter(Boolean));
      expect(
        desks.size,
        `${file} cites ${cited.length} reference(s) from ${desks.size} publication(s): ${[...desks].join(", ")}`,
      ).toBeGreaterThanOrEqual(2);
    }
  });

  it("should point every cited reference at a record that exists", () => {
    // An evidence line naming a reference that was never harvested reads as proof and is not.
    const refs = join(BASE, "references");
    const known = new Set(
      dirsUnder(refs).flatMap((family) =>
        dirsUnder(join(refs, family)).map((id) => id),
      ),
    );
    for (const file of markdownIn(join(BASE, "treatments"))) {
      const text = readFileSync(join(BASE, "treatments", file), "utf8");
      for (const [, id] of text.matchAll(/^- evidence:\s*(\S+)/gm))
        expect(
          known.has(id),
          `${file} cites ${id}, which is not in the corpus`,
        ).toBe(true);
    }
    for (const file of markdownIn(join(BASE, "directions"))) {
      const text = readFileSync(join(BASE, "directions", file), "utf8");
      const from = text.match(/^- measuredFrom:\s*(\S+)/m);
      if (from)
        expect(
          known.has(from[1]),
          `${file} is measured from ${from[1]}, not in the corpus`,
        ).toBe(true);
    }
  });

  it("should keep both indexes generated rather than hand-edited", () => {
    for (const name of ["INDEX-BY-ARTIFACT.md", "INDEX-BY-LEVER.md"]) {
      const path = join(BASE, name);
      if (!existsSync(path)) continue;
      expect(
        readFileSync(path, "utf8"),
        `${name} carries no generated marker`,
      ).toContain(GENERATED_MARKER);
    }
  });

  it("should keep a method with a yield log, so the next family knows which pool paid", () => {
    const method = join(BASE, "METHOD.md");
    if (!existsSync(method)) return;
    const text = readFileSync(method, "utf8");
    expect(text, "METHOD.md carries no yield table").toMatch(
      /\|\s*family\s*\|\s*archive\s*\|/i,
    );
  });
});
