/**
 * THE FLOOR UNDER THE DESIGN BASE. Collecting is not the deliverable.
 *
 * The branch this work replaces died at 112 harvested thumbnails and four written notes: a corpus
 * that grows by harvesting and never by judgement reaches no pixel and teaches nothing. These are
 * the three floors that make that outcome fail loudly instead of quietly.
 *
 *   1. Every reference carries the five sections a judgement needs — including what was NOT
 *      verified, which is the section a hurried harvest drops first.
 *   2. Every treatment cites two independent references. One use is a publication's habit; two is
 *      a practice. A treatment that cannot find its second reference is not filed, and that is the
 *      guard working rather than an obstacle to route around.
 *   3. Both indexes are generated. Two families harvested in parallel — which the methodology
 *      explicitly allows — would conflict on a hand-edited index.
 */
import { describe, it, expect } from "bun:test";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..", "..", "..");
const BASE = join(ROOT, "docs", "design-base");

const REQUIRED_NOTE_SECTIONS = [
  "## What it is",
  "## What it does with information",
  "## What it does with style",
  "## What is transferable",
  "## What was not verified",
];

const GENERATED_MARKER =
  "<!-- generated by scripts/design-base/build-indexes.mjs — do not edit -->";

function dirsUnder(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path).filter((n) => statSync(join(path, n)).isDirectory());
}

function markdownIn(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path).filter((f) => f.endsWith(".md"));
}

describe("the design base", () => {
  it("should give every reference the five sections a judgement needs", () => {
    const refs = join(BASE, "references");
    for (const family of dirsUnder(refs))
      for (const id of dirsUnder(join(refs, family))) {
        const notes = join(refs, family, id, "NOTES.md");
        expect(existsSync(notes), `${family}/${id} has no NOTES.md`).toBe(true);
        const text = readFileSync(notes, "utf8");
        for (const section of REQUIRED_NOTE_SECTIONS)
          expect(text, `${family}/${id} is missing "${section}"`).toContain(
            section,
          );
      }
  });

  it("should back every treatment with at least two independent references", () => {
    for (const file of markdownIn(join(BASE, "treatments"))) {
      const text = readFileSync(join(BASE, "treatments", file), "utf8");
      const evidence = [...text.matchAll(/^- evidence:\s*(\S+)/gm)].map(
        (m) => m[1],
      );
      expect(
        new Set(evidence).size,
        `${file} cites ${new Set(evidence).size} distinct reference(s)`,
      ).toBeGreaterThanOrEqual(2);
    }
  });

  it("should point every cited reference at a record that exists", () => {
    // An evidence line naming a reference that was never harvested reads as proof and is not.
    const refs = join(BASE, "references");
    const known = new Set(
      dirsUnder(refs).flatMap((family) =>
        dirsUnder(join(refs, family)).map((id) => id),
      ),
    );
    for (const file of markdownIn(join(BASE, "treatments"))) {
      const text = readFileSync(join(BASE, "treatments", file), "utf8");
      for (const [, id] of text.matchAll(/^- evidence:\s*(\S+)/gm))
        expect(
          known.has(id),
          `${file} cites ${id}, which is not in the corpus`,
        ).toBe(true);
    }
    for (const file of markdownIn(join(BASE, "directions"))) {
      const text = readFileSync(join(BASE, "directions", file), "utf8");
      const from = text.match(/^- measuredFrom:\s*(\S+)/m);
      if (from)
        expect(
          known.has(from[1]),
          `${file} is measured from ${from[1]}, not in the corpus`,
        ).toBe(true);
    }
  });

  it("should keep both indexes generated rather than hand-edited", () => {
    for (const name of ["INDEX-BY-ARTIFACT.md", "INDEX-BY-LEVER.md"]) {
      const path = join(BASE, name);
      if (!existsSync(path)) continue;
      expect(
        readFileSync(path, "utf8"),
        `${name} carries no generated marker`,
      ).toContain(GENERATED_MARKER);
    }
  });

  it("should keep a method with a yield log, so the next family knows which pool paid", () => {
    const method = join(BASE, "METHOD.md");
    if (!existsSync(method)) return;
    const text = readFileSync(method, "utf8");
    expect(text, "METHOD.md carries no yield table").toMatch(
      /\|\s*family\s*\|\s*archive\s*\|/i,
    );
  });
});
