/**
 * WHAT THIS GUARD CATCHES, AND WHAT IT PROVABLY DOES NOT.
 *
 * `twin/MATRIX.md` is generated by `twin/scripts/matrix.mjs`, and that script has always carried a
 * `--check` mode that exits 1 when the file has drifted from the tree. **Nothing ran it.** Measured
 * 2026-08-11: `--check` was RED in the working tree, and a search across the repository found it
 * invoked by no test, no package script and no hook — the commit that built it claims both
 * generated files "have checks that go red", and one of the two had no way to.
 *
 * That is the exact failure the script's own header is about: *"a count of '11 orphan stills' was
 * reported, repeated four times across one night, written into HANDOVER.md, and turned out to be
 * ONE the first time anybody ran the check."* A generator with an unrun check is a hand-written
 * table wearing a script's clothes.
 *
 * So this runs the real CLI, in a subprocess, and asserts its EXIT CODE — not a re-implementation
 * of the comparison, because a second copy of the rule is the drift this whole file is about, and
 * because the exit code is the half a caller (`bun run matrix:check`, a hook, CI) actually reads.
 * `package.json` gains `matrix:check` in the same commit so there is a name to call.
 *
 * WHAT IT PROVABLY DOES NOT CATCH.
 *
 * 1. WHETHER THE MATRIX IS RIGHT. It proves the file agrees with `readBeats()`. If the reader
 *    misjudges a beat, the table is confidently wrong and this is green. The script's own header
 *    names the one judgement it makes (a video beat's final frame is not static proof).
 * 2. A BEAT WHOSE BRIEF DECLARES NO TYPE. Those land in the "Beats with no `BRIEF.md`" list and
 *    the tables simply do not count them, so the matrix under-reports and stays self-consistent.
 *    Four directories are in that list today and the section's title is wrong about three of them:
 *    `co2-suisse`, `mapscrolly-one-map-europe-carbon` and `scrolly-one-chart-swiss-life-expectancy`
 *    all HAVE a `BRIEF.md`; what they lack is a `**Type:**` line for `matrix.mjs:66` to read
 *    (`co2-suisse`'s brief is in French and says "Médium / format :"). The consequence the owner
 *    reported is real: the scrolly column shows four beats where six exist. Those three briefs and
 *    `portrait-aspect-probe` — a probe workspace that is not a beat at all — belong to other
 *    chantiers, so the residue is reported here rather than edited.
 * 3. A BEAT NOBODY HAS COMMITTED YET. `MATRIX.md` is a committed artifact, so `matrix.mjs` skips a
 *    `proof/<name>/` that git does not track — on BOTH its paths, write and check, because a rule
 *    two callers read two ways is the drift that script exists to end. A new beat enters the table
 *    the moment it is committed. This was not cosmetic: seven sessions share this worktree, and
 *    reddening everybody's check because one of them has an uncommitted folder is how a check
 *    becomes a thing people learn to regenerate past.
 *
 * THE MUTATION THAT REDDENS IT, run in a copy of the tree under /tmp, never here: one row of
 * `MATRIX.md` edited by hand (`static-world-population` -> `static-world-populations`).
 *
 *   Expected: "bun scripts/matrix.mjs --check exits 0"
 *   Received: "bun scripts/matrix.mjs --check exits 1: MATRIX.md has drifted from the tree.
 *              Run: bun scripts/matrix.mjs"
 *   (fail) the generated coverage map still describes the tree > should match what
 *          scripts/matrix.mjs produces from proof/ today
 *    1 pass · 1 fail
 *
 * And a second, from the same copy: `git add`-ing the untracked beat so it becomes tracked reddens
 * the check too, which is blind spot 3 working in the direction that matters — a beat enters the
 * table when it is committed, and the table has to be regenerated then.
 *
 * And the mutation that reddened the FIRST DRAFT OF THIS FILE, which is the more useful one: the
 * same hand-edit, with a `--help` liveness probe above it. GREEN — because the probe rewrote
 * MATRIX.md before the check read it. `matrix.mjs` now exits 2 on an argument it does not know
 * (verified: `bun scripts/matrix.mjs --chek` -> exit 2, MATRIX.md untouched) and this file spawns
 * the script exactly once.
 */
import { describe, it, expect } from "bun:test";
import { join } from "node:path";

const TWIN = join(import.meta.dirname, "..", "..", "..");

// ONE spawn, read twice. Running the script a second time to "check the spawn works" is what broke
// the first draft of this file: `matrix.mjs`'s write was the else-branch of `--check`, so probing
// it with `--help` REGENERATED MATRIX.md and the assertion below then compared the file to itself.
// Green, always, and repairing the drift it was written to report. The script now refuses an
// argument it does not know (exit 2) and this file spawns once.
const RUN = Bun.spawnSync(["bun", "scripts/matrix.mjs", "--check"], {
  cwd: TWIN,
});
const SAID = new TextDecoder()
  .decode(RUN.exitCode === 0 ? RUN.stdout : RUN.stderr)
  .trim();

describe("the generated coverage map still describes the tree", () => {
  it("should actually have run the generator's own --check", () => {
    // The premise, pinned: a spawn that never started, or a bun that could not find the script,
    // would make the assertion below read a meaningless status. It must have RUN and it must have
    // spoken about the file it was asked about.
    expect([
      RUN.exitCode === 0 || RUN.exitCode === 1,
      /MATRIX\.md/.test(SAID),
    ]).toEqual([true, true]);
  });

  it("should match what scripts/matrix.mjs produces from proof/ today", () => {
    expect(
      RUN.exitCode === 0
        ? "bun scripts/matrix.mjs --check exits 0"
        : `bun scripts/matrix.mjs --check exits ${RUN.exitCode}: ${SAID}`,
    ).toBe("bun scripts/matrix.mjs --check exits 0");
  });
});
